from sqlmodel import create_engine
from .config import Config


engine = create_engine(Config.database_url, echo=True)

"""
create_engine -> SQLAlchemy function that establishes a connection to your database.
echo=True -> enables logging of all SQL statements generated by SQLAlchemy, which is useful for debugging.
"""